name: Deploy new firefox release
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.7.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        run: make build-all
      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{d08a826c-3581-4f5a-a1c6-39b4b22ca6e7}'
          xpi: "releases/latest_firefox.xpi"
          manifest: "manifest_firefox.json"
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
